# Generated by Django 4.1.4 on 2022-12-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=15, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
